services:
  db:
    image: postgres:latest
    container_name: abit-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  abit-app:
    build: .
    container_name: abit-parser
    volumes:
      - ./config.toml:/app/config.toml
    depends_on:
      - db

volumes:
  postgres_data:
