[package]
name = "edbo_core"
version = "0.0.1"
authors = ["Alex Kovalov <alexkovalevkpi@gmail.com>"]

edition = "2024"
rust-version = "1.89"

categories = ["simulation"]
keywords = ["applicants", "education"]

readme = "../README.md"
license = "MIT"
repository = "https://github.com/xairaven/abit-rs"

[lints]
workspace = true

[dependencies]
dotenvy = "0.15.7"
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.142"
sqlx = { version = "0.8", features = [ "postgres", "runtime-tokio", "json" ] }
thiserror = "2.0.14"
tokio = { version = "1.47.1", features = ["full"] }
